// export { default as BannerSearch } from "./BannerSearch";
// export { default as FeaturedProperties } from "./FeaturedProperties";
export { default as Footer } from "./Footer";
export { default as Map } from "./Map";
export { default as Navbar } from "./Navbar";
export { default as Reviews } from "./Reviews";
export { default as Search } from "./Search";
export { default as Carousel } from "./Carousel";
export { default as Pagination } from "./Pagination";
export { default as Property } from "./Property";
